
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 20 20:06:05 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 17;
  public static final int MOD = 15;
  public static final int READ = 18;
  public static final int IDENT = 33;
  public static final int PLUS = 2;
  public static final int RBRACE = 24;
  public static final int RPAREN = 3;
  public static final int EQUAL = 4;
  public static final int CHAR = 30;
  public static final int SEMI = 5;
  public static final int PLUS_PLUS = 20;
  public static final int LBRACK = 16;
  public static final int RETURN = 6;
  public static final int MINUS_EQUAL = 26;
  public static final int MOD_EQUAL = 29;
  public static final int DIV_EQUAL = 28;
  public static final int LBRACE = 23;
  public static final int LPAREN = 7;
  public static final int COMMA = 8;
  public static final int NUMBER = 31;
  public static final int EOF = 0;
  public static final int PLUS_EQUAL = 25;
  public static final int DIV = 14;
  public static final int PROG = 9;
  public static final int MINUS = 12;
  public static final int CONST = 21;
  public static final int PRINT = 10;
  public static final int error = 1;
  public static final int NEW = 19;
  public static final int BOOL = 32;
  public static final int MUL_EQUAL = 27;
  public static final int MINUS_MINUS = 22;
  public static final int MUL = 13;
  public static final int VOID = 11;
}

