
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
  public static final int IDENT = 15;
  public static final int PLUS = 11;
  public static final int RPAREN = 7;
  public static final int EQUAL = 12;
  public static final int SEMI = 5;
  public static final int RETURN = 10;
  public static final int LPAREN = 6;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int PROG = 2;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int VOID = 13;
  public static final int MINUS = 19;
  public static final int MUL = 20;
  public static final int DIV = 16;
  public static final int MOD = 17;
  public static final int LBRACK = 21;
  public static final int RBRACK = 22;
  public static final int READ = 3;
  public static final int NEW = 4;
  public static final int PLUS_PLUS = 18;
  public static final int MINUS_MINUS = 23;
  public static final int LBRACE = 24;
  public static final int RBRACE = 25;
  public static final int PLUS_EQUAL = 26;
  public static final int MINUS_EQUAL = 27;
  public static final int MUL_EQUAL = 28;
  public static final int DIV_EQUAL = 29;
  public static final int MOD_EQUAL = 30;
  public static final int CHAR = 31;
}

